name: Build macOS App (Latest Xcode)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show available Xcode versions
        run: ls -1 /Applications | grep Xcode

      - name: Select latest available Xcode version
        run: |
          sudo xcode-select -s /Applications/$(ls /Applications | grep Xcode | sort -rV | head -n 1)

      - name: Confirm selected Xcode version
        run: xcodebuild -version

      - name: Build ColorGraphApp
        run: |
          xcodebuild \
            -project "ColorGraphApp.xcodeproj" \
            -scheme "ColorGraphApp" \
            -destination 'platform=macOS' \
            clean build

      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project "ColorGraphApp.xcodeproj" \
            -scheme "ColorGraphApp" \
            -destination 'platform=macOS' \
            test
